import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Product from "./Projects/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ethan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <html lang="en">
      <head>
      <link rel="icon" href="/images/main.png" />
      </head>
      <body className={inter.className}>{children}
        
              </body>
    </html>
  );
}
